title: [Cybersecurity Projects by Felix Serrano Jr.]
description: [The goal of this page is to showcase my understanding of cybersecurity tools and concepts.]
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
